name: Android CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    env:
      android:
        api: 29
        arch: 'x86'
      variant: 'debug'
      gradleTask: 'assembleDebug'

  test:
    name: Run Test Suite [Unit, Instrumented]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Execute Unit Tests (gradlew test)
        run: bash ./gradlew test --stacktrace

      - name: Execute Instrumentation Tests (gradlew connectedCheck - api $android.api)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: $android.api
          target: default
          arch: $android.arch
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

  generateArtifacts:
    name: Generate Debug APK artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build $variant APK
        run: bash ./gradlew $gradleTask --stacktrace

      - name: Upload $variant APK
        uses: actions/upload-artifact@v1
        with:
          name: app-$variant-${{ github.run_number }}-$variant
          path: app/build/outputs/apk/$build_type/app-$variant.apk
